### ISSUE TITLE
 certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by holger-dunst** [mozilla-iot/meross-adapter#6]
I am using the docker version (0.12.0) of the webthings-gateway running on a raspberry pi in host mode. I entered my meross credentials and get the following stacktrace in the logs:

2020-04-25 17:36:36.595 ERROR  : meross-adapter: Traceback (most recent call last):
2020-04-25 17:36:36.597 ERROR  : meross-adapter:   File "/home/node/.mozilla-iot/addons/meross-adapter/main.py", line 30, in <module>
2020-04-25 17:36:36.598 ERROR  : meross-adapter:     _ADAPTER = MerossAdapter(verbose=_DEBUG)
2020-04-25 17:36:36.599 ERROR  : meross-adapter:   File "/home/node/.mozilla-iot/addons/meross-adapter/pkg/meross_adapter.py", line 47, in __init__
2020-04-25 17:36:36.600 ERROR  : meross-adapter:     self.manager.start()
2020-04-25 17:36:36.603 ERROR  : meross-adapter:   File "/home/node/.mozilla-iot/addons/meross-adapter/lib/meross_iot/manager.py", line 45, in start
2020-04-25 17:36:36.604 ERROR  : meross-adapter:     self._cloud_client.connect()
2020-04-25 17:36:36.605 ERROR  : meross-adapter:   File "/home/node/.mozilla-iot/addons/meross-adapter/lib/meross_iot/cloud/client.py", line 167, in connect
2020-04-25 17:36:36.606 ERROR  : meross-adapter:     self._mqtt_client.connect(self._domain, self._port, keepalive=30)
2020-04-25 17:36:36.610 ERROR  : meross-adapter:   File "/home/node/.mozilla-iot/addons/meross-adapter/lib/paho/mqtt/client.py", line 937, in connect
2020-04-25 17:36:36.611 ERROR  : meross-adapter:     return self.reconnect()
2020-04-25 17:36:36.612 ERROR  : meross-adapter:   File "/home/node/.mozilla-iot/addons/meross-adapter/lib/paho/mqtt/client.py", line 1100, in reconnect
2020-04-25 17:36:36.614 ERROR  : meross-adapter:     sock.do_handshake()
2020-04-25 17:36:36.615 ERROR  : meross-adapter:   File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
2020-04-25 17:36:36.616 ERROR  : meross-adapter:     self._sslobj.do_handshake()
2020-04-25 17:36:36.617 ERROR  : meross-adapter: ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

**Comment by mrstegeman** [comment]
Seems to be working for me inside Docker. Is the clock set properly on your RPi?

**Comment by holger-dunst** [comment]
I think so.
Here the snipped from my docker-compose file:

  webthings-gateway:
    image:  mozillaiot/gateway:latest
    container_name: webthings-gateway
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/docker/volumes/webthings-gateway:/home/node/.mozilla-iot
    environment:
      - TZ=Europe/Berlin

**Comment by mrstegeman** [comment]
Right, but if you run `date` on your RPi (the host), does it look correct?

**Comment by holger-dunst** [comment]
Yes, like I said before.

Here an example:
pi@smarthome:~ $ timedatectl status && date
               Local time: So 2020-04-26 18:23:49 CEST
           Universal time: So 2020-04-26 16:23:49 UTC
                 RTC time: n/a
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
          
So 26. Apr 18:23:49 CEST 2020

**Comment by mrstegeman** [comment]
Hmm, I'm really not sure then. It's possible that their server is misconfigured right now. I'm hitting a US server, I assume, but you may be hitting an EU one.
