### ISSUE TITLE
Probably some sort of auth error

### ISSUE THREAD

**Issue by stutrek** [mozilla-iot/meross-adapter#7]
When I leave the meross adapter running for a long time I start to get this error:

```
2020-06-06 09:29:35.000 ERROR  : meross-adapter: Exception in thread Thread-25:
2020-06-06 09:29:35.005 ERROR  : meross-adapter: Traceback (most recent call last):
2020-06-06 09:29:35.005 ERROR  : meross-adapter:   File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
2020-06-06 09:29:35.005 ERROR  : meross-adapter:     self.run()
2020-06-06 09:29:35.006 ERROR  : meross-adapter:   File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
2020-06-06 09:29:35.006 ERROR  : meross-adapter:     self._target(*self._args, **self._kwargs)
2020-06-06 09:29:35.006 ERROR  : meross-adapter:   File "/usr/local/lib/python3.7/site-packages/gateway_addon/addon_manager_proxy.py", line 480, in set_prop_fn
2020-06-06 09:29:35.007 ERROR  : meross-adapter:     prop.set_value(msg['data']['propertyValue'])
2020-06-06 09:29:35.007 ERROR  : meross-adapter:   File "/Users/stu/.mozilla-iot/addons/meross-adapter/pkg/meross_property.py", line 124, in set_value
2020-06-06 09:29:35.007 ERROR  : meross-adapter:     channel=self.device.channel
2020-06-06 09:29:35.007 ERROR  : meross-adapter:   File "/Users/stu/.mozilla-iot/addons/meross-adapter/lib/meross_iot/cloud/devices/power_plugs.py", line 162, in turn_off
2020-06-06 09:29:35.008 ERROR  : meross-adapter:     return self._channel_control_impl(c, 0, callback=callback)
2020-06-06 09:29:35.008 ERROR  : meross-adapter:   File "/Users/stu/.mozilla-iot/addons/meross-adapter/lib/meross_iot/cloud/devices/power_plugs.py", line 35, in _channel_control_impl
2020-06-06 09:29:35.008 ERROR  : meross-adapter:     return self._togglex(channel, status, callback=callback)
2020-06-06 09:29:35.008 ERROR  : meross-adapter:   File "/Users/stu/.mozilla-iot/addons/meross-adapter/lib/meross_iot/cloud/devices/power_plugs.py", line 29, in _togglex
2020-06-06 09:29:35.008 ERROR  : meross-adapter:     return self.execute_command("SET", TOGGLEX, payload, callback=callback)
2020-06-06 09:29:35.009 ERROR  : meross-adapter:   File "/Users/stu/.mozilla-iot/addons/meross-adapter/lib/meross_iot/cloud/device.py", line 126, in execute_command
2020-06-06 09:29:35.009 ERROR  : meross-adapter:     return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
2020-06-06 09:29:35.009 ERROR  : meross-adapter:   File "/Users/stu/.mozilla-iot/addons/meross-adapter/lib/meross_iot/cloud/client.py", line 300, in execute_cmd
2020-06-06 09:29:35.009 ERROR  : meross-adapter:     raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
2020-06-06 09:29:35.009 ERROR  : meross-adapter: meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```

If I halt and restart the server, I get this:
```
2020-06-06 10:14:41.864 ERROR  : Failed to get property on: getProperty: device: meross-1811136298913529086234298f1d51d2-0 not found.
2020-06-06 10:14:41.864 ERROR  : Failed to get property on: getProperty: device: meross-1811136298913529086234298f1d51d2-1 not found.
2020-06-06 10:14:41.864 ERROR  : Failed to get property on: getProperty: device: meross-1811136298913529086234298f1d51d2-3 not found.
2020-06-06 10:14:41.865 ERROR  : Failed to get property on: getProperty: device: meross-1811136298913529086234298f1d51d2-2 not found.
2020-06-06 10:14:41.865 ERROR  : Failed to get property on: getProperty: device: meross-1811136298913529086234298f1d51d2-4 not found.
2020-06-06 10:14:41.865 ERROR  : Failed to get property on: getProperty: device: meross-1811136298913529086234298f1d51d2-5 not found.
```

Then, if I open the settings, and save the same login information, it works again.

Using on a Mac.

**Comment by stutrek** [comment]
It appears to be this bug. The author of the underlying library is working on it. I'll do my best to keep tabs on it and post again when the new version is released.

https://github.com/albertogeniola/MerossIot/issues/97

**Comment by mrstegeman** [comment]
Thanks for tracking that down!
